# Generated by Django 2.2.12 on 2021-12-08 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=30)),
                ('prezime', models.CharField(max_length=70)),
                ('datum_rodenja', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korisnicko_ime', models.CharField(max_length=20)),
                ('bio', models.CharField(max_length=120)),
                ('slika_profil', models.ImageField(upload_to='')),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Korisnik')),
            ],
        ),
        migrations.CreateModel(
            name='Objava',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slika_objava', models.ImageField(upload_to='')),
                ('opis_objava', models.CharField(max_length=500)),
                ('vrijeme_objava', models.DateTimeField()),
                ('lajk_objava', models.IntegerField()),
                ('profil_objava', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_komentar', models.CharField(max_length=500)),
                ('vrijeme_komentar', models.DateTimeField()),
                ('lajk_komentar', models.IntegerField()),
                ('objava_komentar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Objava')),
                ('profil_komentar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profil')),
            ],
        ),
    ]
