# Generated by Django 4.0.1 on 2022-02-20 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_remove_profil_korisnicko_ime_remove_profil_korisnik_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='slika_profil',
            field=models.ImageField(default='index.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profil',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profil',
            name='bio',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
