# Generated by Django 4.0.1 on 2022-02-22 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_komentar_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='komentar',
            name='post',
        ),
        migrations.RemoveField(
            model_name='komentar',
            name='user',
        ),
    ]
