# Generated by Django 4.0.1 on 2022-02-21 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_profil_slika_profil_profil_user_alter_profil_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objava',
            name='lajk_objava',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='objava',
            name='profil_objava',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='objava',
            name='slika_objava',
            field=models.ImageField(upload_to='static/image'),
        ),
        migrations.AlterField(
            model_name='objava',
            name='vrijeme_objava',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='slika_profil',
            field=models.ImageField(default='static/image/default_avatar.png', upload_to='static/image'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
