# Generated by Django 4.0.1 on 2022-02-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_komentar_post_remove_komentar_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentar',
            name='title',
            field=models.CharField(default='a', max_length=100),
        ),
    ]
