# Generated by Django 4.0.1 on 2022-02-21 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_objava_profil_objava'),
    ]

    operations = [
        migrations.AddField(
            model_name='objava',
            name='profil_objava',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.profil'),
            preserve_default=False,
        ),
    ]
