# Generated by Django 4.0.1 on 2022-02-22 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_komentar_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentar',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='post_comm', to='main.objava'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='komentar',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_comm', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
