# Generated by Django 4.0.1 on 2022-02-22 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_komentar_post_komentar_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='komentar',
            name='title',
        ),
    ]
