# Generated by Django 4.0.1 on 2022-02-21 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_komentar_lajk_komentar_komentar_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='komentar',
            name='active',
        ),
    ]
