# Generated by Django 4.0.1 on 2022-02-22 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_remove_komentar_lajk_komentar_komentar_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='komentar',
            name='active',
        ),
        migrations.RemoveField(
            model_name='objava',
            name='lajk_objava',
        ),
        migrations.AddField(
            model_name='objava',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_like', to='main.objava')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
